CREATE TABLE IF NOT EXISTS {{table_name}} (
    id INTEGER NOT NULL DEFAULT 1 PRIMARY KEY AUTOINCREMENT,
    time TEXT NOT NULL DEFAULT 0,
    summary INTEGER NOT NULL DEFAULT 0,
    information TEXT NOT NULL DEFAULT ''
)