CREATE TABLE IF NOT EXISTS accounts (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	balance DECIMAL NOT NULL DEFAULT 0,
	currency TEXT NOT NULL  DEFAULT 'BYN',
	table_name TEXT NOT NULL
);